### ISSUE TITLE
Test request: OVH Baremetal servers

### ISSUE THREAD

**Issue by bretton** [depenguin-me/depenguin-run#41]
Test Request: OVH Baremetal servers

https://www.ovhcloud.com/en/bare-metal/

Multiple tiers/ranges of servers with common entry level disk setup of 2 x 2TB or 2 x 512GB SSD:
* Kimsufi
* Rise
* Advance
* Game
* Scale
* High Grade

Linux based rescue system
https://docs.ovh.com/gb/en/dedicated/ovh-rescue/

**Comment by bretton** [comment]
This can be closed with #50 however some more tests may be useful

**Comment by bretton** [comment]
related to #51

**Comment by hpcharles** [comment]
I've tested on  a KS-16 OVH machine. I had to replace   "mkisofs:mkisofs"
by "genisoimage:genisoimage"

Once qemu has booted, I can not ssh -p 1022 msfbsd@... to the  machine..

**Comment by bretton** [comment]
* KS-GAME-1 - Core i7-4790K - Installation worked using GPT(BIOS) in bsdinstall (PR https://github.com/depenguin-me/depenguin-run/pull/50)
* KS-16 - Xeon E3-1245v2 - replace "mkisofs:mkisofs" with "genisoimage:genisoimage"

**Comment by bretton** [comment]
> Once qemu has booted, I can not ssh -p 1022 msfbsd@... to the machine..

general diagnostics: is port 1022 open? is there an error message?

**Comment by hpcharles** [comment]
> > Once qemu has booted, I can not ssh -p 1022 msfbsd@... to the machine..
> 
> general diagnostics: is port 1022 open? is there an error message?

There is no firewall, no error message

**Comment by hpcharles** [comment]
> > > Once qemu has booted, I can not ssh -p 1022 msfbsd@... to the machine..
> > 
> > 
> > general diagnostics: is port 1022 open? is there an error message?
> 
> There is no firewall, no error message

It ask to accept the new key (sshd works) "The authenticity of host .... an't be established

But fails to identificate with public key : 
debug1: Trying ... all my public key 
debug1: No more authentication methods to try.
msfbsd@localhost: Permission denied (publickey).

**Comment by bretton** [comment]
I can confirm that `mkisofs:mkisofs` needs replacing with `genisoimage:genisoimage` on 

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

However it works fine for me when I access mfsbsd on KS-16 host on OVH. 

How are you passing in your public key? I'm running `./run.sh http://my.host/keys.txt` where `keys.txt` matches an `.ssh/authorized_keys` file from a server.

**Comment by bretton** [comment]
follow up: unattended install completed, but host didn't boot up with reachable network interface. KVM is $40/month and no IPMI. It should pick up correct interface name on firstboot. When I try go back to rescue it says an intervention is underway, limiting my ability to try install again right now. Will pick up in the week as time permits.

**Comment by bretton** [comment]
for interest sake, KVM is Lantronix Spider

**Comment by bretton** [comment]
Disks appear to be on a SAN device and won't boot. Tried multiple times. Screenshot attached.
![Screenshot](https://github.com/depenguin-me/depenguin-run/assets/4481592/42b26707-7898-4f15-a668-4a26abf1d658)

**Comment by bretton** [comment]
Updated installer script runs fine. There is a delay between creating iso and detecting disks, but everything works to get mfsbsd image running and reachable. 

The server actually has 3 disks, and when configured for unattended install with raidz1 then it boots fine

```
bretton@ns523785:~ $ freebsd-version
14.0-RELEASE
```

**Comment by bretton** [comment]
@hpcharles I think we need to try debug your ssh key import. Do you have your `id_rsa.pub` accessible via a url?

**Comment by bretton** [comment]
Original issue can be closed again with [PR-78](https://github.com/depenguin-me/depenguin-run/pull/78)
