### ISSUE TITLE
mkisofs not found

### ISSUE THREAD

**Issue by nkfilis** [depenguin-me/depenguin-run#51]
It seems, depending on the debian version used for the rescue image, you need to install a different package. In the case of a OVH/Kimsufi KS-GAME-1, I needed to remove the `"mkisofs:mkisofs"` from the `DEPS` variable and installed `xorriso` and `genisoimage` packages by hand. 
It looks like the OVH rescue-pro uses Debian Jessie, but I'm not very familiar with those things.

**Comment by bretton** [comment]
* boot into recovery by clicking “Netboot”, then “Rescue” and select “rescue-pro” in the menu
* boot into recovery by clicking “Netboot”, then “Rescue” and select “rescue64-pro” in the menu

It looks like this is the most information page for info on OVH rescue and patched kernel builds
https://last-public-ovh-kernel.snap.mirrors.ovh.net/

latest build
https://last-public-ovh-kernel.snap.mirrors.ovh.net/builds/5.15.59/2413965/

and Debian Buster / Debian 10 seems to be the latest at
https://last-public-ovh-kernel.snap.mirrors.ovh.net/debian/dists/
and is EOL for updates as of Aug 2022.

**Comment by grembo** [comment]
@bretton I would suggest to allow specifying multiple potential packages per dependency, then we can just try them all. I can add soonish.
