### ISSUE TITLE
ovmf package missing on Debian 10

### ISSUE THREAD

**Issue by nkfilis** [depenguin-me/depenguin-run#67]
The current OVH rescue system is based on Debian 10 and it needs the `ovmf` package to be installed in order for qemu to run properly

**Comment by bretton** [comment]
If you up for testing in meantime - regular file will be updated, this removed later
```
wget https://depenguin.me/ovh-run.sh \
&& chmod +x ovh-run.sh \
&& ./ovh-run.sh authorized_keys ... 
```

**Comment by bretton** [comment]
I've merged on assumption it works. It works with Hetzner test. Feel free to re-open if problems.
