### ISSUE TITLE
Testing Hetzner EX44 (NVMe)

### ISSUE THREAD

**Issue by grembo** [depenguin-me/depenguin-run#79]
This server works mostly out of the box, but requires a special network driver from ports to work.

In this test, the network adapter was a _Realtek RTL8125 2.5GbE Controller_ (vendor=0x10ec device=0x8125). This should work with `net/realtek-re-kmod`, but at the time of writing (March 2024) it doesn't. Instead, `net/realtek-re-kmod198` is required (see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=275882 for details).

----

After finishing the installation, but before rebooting, drop into a shell and install the driver:

```
pkg install realtek-re-kmod198
```

Then adapt _/boot/loader.conf_ to make use of it:

```
if_re_load="YES"
if_re_name="/boot/modules/if_re.ko"
hw.re.max_rx_mbuf_sz="2048"  # optional
```

Finally configure the interface in _/etc/rc.conf_:

```
ifconfig_re0_name="untrusted"

ifconfig_untrusted="up"
ifconfig_untrusted_ipv6="up"
ifconfig_untrusted_aliases="inet 1.2.3.4/32 inet6 2a01:4f8:1:2a::2/64"

static_routes="gateway default"
route_gateway="-host 1.2.3.1 -interface untrusted"
route_default="default 1.2.3.1"

ipv6_defaultrouter="fe80::1%untrusted"
```

Legend:
- `1.2.3.4`: host IPv4 IP
- `1.2.3.1`: IPv4 default gateway
- `2a01:4f8:1:2a::2`: host IPv6 IP

**Comment by bretton** [comment]
Realtek cards is now catered for with https://github.com/depenguin-me/depenguin-builder/pull/25
