### ISSUE TITLE
Please provide a 13.3 ISO

### ISSUE THREAD

**Issue by grembo** [depenguin-me/depenguin-run#84]
Now that 13.2 is EoL, it would be great if we could get a 13.3 ISO (as installing 13.2 and then upgrading is not a real option anymore). Prettyplease? ;)

**Comment by bretton** [comment]
can test so long
```
wget https://depenguin.me/qa.sh
chmod +x qa.sh
./qa.sh <key-url>
``

**Comment by bretton** [comment]
closing this as 13.4 is available
